### ISSUE TITLE
[ENHANCEMENT] Smooth Fov

### ISSUE THREAD

**Issue by DankBoi293** [XroixHD/MCBE-Win10-FOV-Changer#119]
Smooth Fov?

somthing like 
```python
original-fov = 100
zoom-fov=30
current-fov = 100
def smooth-fov(): 
    
    while current-fov > zoom-fov: 
        current-fov -= 1
        # apply
```
idk if this works, my python is a little rusty. I use the FOV Changer everyday and I love it. Thanks.

**Comment by XroixHD** [comment]
My private version (that now uses dll injection, thus c++) has already implemented it.  
But thanks for idea and feedback! 👍

**Comment by DankBoi293** [comment]
oh. well....ok.
