### ISSUE TITLE
Doesn’t work in recent beta

### ISSUE THREAD

**Issue by somefosterkid** [XroixHD/MCBE-Win10-FOV-Changer#124]
Would I be able to modify any of the files to make it work even though the version isn’t “supported”?

**Comment by BoredSathvik** [comment]
Hello, i don't think you can do that as fov changer fetches pointers from an api, you might be able to change the code to fetch the pointers from a json file if you know about how apis and fetch in python works .-.(i did not exprement with this stuff i think there is a thing in a storage.json called api it may work)

**Comment by XroixHD** [comment]
I usually only update to the latest version (no betas) because most people play on them *and I wan't to avoid more work*

**Comment by somefosterkid** [comment]
No problem, thanks for the quick response I’ll just wait until the new full update is out if you’re able to update it then. Thanks again!
