### ISSUE TITLE
Win64:Trojan-gen in Avast

### ISSUE THREAD

**Issue by geostuff27** [XroixHD/MCBE-Win10-FOV-Changer#125]
The zip file is flagged as containing Win64:Trojan-gen by Avast, blocking download of the complete file

**Comment by XroixHD** [comment]
Sadly, that's a common problem with [PyInstaller](https://github.com/pyinstaller/pyinstaller) frozen python scripts. An article discussing this in more detail: https://stevepython.wordpress.com/2019/01/22/do-avs-treat-python-as-a-virus/
If you don't trust the releases, you can either run the source code directly or freeze it yourself.

**Comment by XroixHD** [comment]
Moved to #3
