### ISSUE TITLE
Incompatible with 1.17

### ISSUE THREAD

**Issue by MaxLaver** [XroixHD/MCBE-Win10-FOV-Changer#129]
With the new 1.17 update to Bedrock, this application is currently incompatible with the game.

![FOV](https://user-images.githubusercontent.com/85573310/121216249-a1232d80-c878-11eb-9e63-53d8bb981d64.png)

**Comment by BoredSathvik** [comment]
wait till he adds it

**Comment by XroixHD** [comment]
Should be supported now
